In [2]:
import numpy as np
from matplotlib import pyplot as plt


In [4]:
class Keyframe:
    def __init__(self, position, orientation, point_cloud, descriptor=None, id=None, timestamp=None):
        self.position = position  # [x, y, z]
        self.orientation = orientation  # Quaternion [qx, qy, qz, qw]
        self.point_cloud = point_cloud  # Full point cloud
        self.descriptor = descriptor  # Optional pose descriptor
        self.id = id  # Unique identifier
        self.timestamp = timestamp  # Optional metadata


In [24]:
pos = np.zeros([3])
look_dir = np.zeros([3])
pc = np.random.randn(10,3)

k = Keyframe(pos, look_dir, pc)

In [25]:
print(k.point_cloud)

[[-1.26358295  0.94975262 -0.07982602]
 [-0.04860726  0.07739919  0.03563413]
 [-1.76053062  0.25221781  2.06674849]
 [-0.31357482 -0.71378819  1.30093419]
 [ 1.16255697 -1.10735484  1.04162651]
 [-0.5409386   0.27120546 -1.12544979]
 [ 0.97120924 -0.50063409 -0.38142702]
 [-0.27253864  0.97673537 -0.51047475]
 [-0.1248554  -0.72294382 -0.20990697]
 [-0.95575627  0.33554606 -0.33605997]]
